ALTER TABLE PetLevelEnergy
ADD
CONSTRAINT pk_PetLevelEnergy PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE PetBreed
ADD 
CONSTRAINT pk_PetBreed PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetType
ADD 
CONSTRAINT pk_PetType PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetState
ADD 
CONSTRAINT pk_PetState PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetIllness
ADD 
CONSTRAINT pk_PetIllness PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Medicine
ADD 
CONSTRAINT pk_Medicine PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Treatment
ADD 
CONSTRAINT pk_Treatment PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetTraining
ADD 
CONSTRAINT pk_PetTraining PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetPhoto
ADD 
CONSTRAINT pk_PetPhoto PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SpaceRequired
ADD 
CONSTRAINT pk_SpaceRequired PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetSize
ADD 
CONSTRAINT pk_PetSize PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE District
ADD 
CONSTRAINT pk_District PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Canton
ADD 
CONSTRAINT pk_Canton PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Province
ADD 
CONSTRAINT pk_Province PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Country
ADD 
CONSTRAINT pk_Country PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetSeverity
ADD 
CONSTRAINT pk_PetSeverity PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Pet
ADD 
CONSTRAINT pk_Pet PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Veterinarian
ADD 
CONSTRAINT pk_Veterinarian PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SizeXFosterHome
ADD 
CONSTRAINT pk_SizeXFosterHome PRIMARY KEY (IdSize)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SizeXFosterHome
ADD 
CONSTRAINT pk_SizeXFosterHome PRIMARY KEY (IdFosterHome)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXTreatment
ADD 
CONSTRAINT pk_PetXTreatment PRIMARY KEY (IdPet)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXTreatment
ADD 
CONSTRAINT pk_PetXTreatment PRIMARY KEY (IdTreatment)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXPetIllness
ADD 
CONSTRAINT pk_PetXPetIllness PRIMARY KEY (IdPet)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXPetIllness
ADD 
CONSTRAINT pk_PetXPetIllness PRIMARY KEY (IdPetIllness)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXMedicine
ADD 
CONSTRAINT pk_PetXMedicine PRIMARY KEY (IdPet)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXMedicine
ADD 
CONSTRAINT pk_PetXMedicine PRIMARY KEY (IdMedicine)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetLevelEnergyXFosterHome
ADD 
CONSTRAINT pk_PetLevelEnergyXFosterHome PRIMARY KEY (IdEnergy)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetLevelEnergyXFosterHome
ADD 
CONSTRAINT pk_PetLevelEnergyXFosterHome PRIMARY KEY (IdFosterHome)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SpaceRequiredXFosterHome
ADD 
CONSTRAINT pk_SpaceRequiredXFosterHome PRIMARY KEY (IdSpaceRequired)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SpaceRequiredXFosterHome
ADD 
CONSTRAINT pk_SpaceRequiredXFosterHome PRIMARY KEY (IdFosterHome)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE FoundReport
ADD 
CONSTRAINT pk_FoundReport PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Match
ADD 
CONSTRAINT pk_Match PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE LostReport
ADD 
CONSTRAINT pk_LostReport PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Adoption
ADD 
CONSTRAINT pk_Adoption PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Rescued
ADD 
CONSTRAINT pk_Rescued PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Donation
ADD 
CONSTRAINT pk_Donation PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Currency
ADD 
CONSTRAINT pk_Currency PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE User
ADD 
CONSTRAINT pk_User PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE ReportList
ADD 
CONSTRAINT pk_ReportList PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Rescuer
ADD 
CONSTRAINT pk_Rescuer PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Adopter
ADD 
CONSTRAINT pk_Adopter PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Calification
ADD 
CONSTRAINT pk_Calification PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE FosterHome
ADD 
CONSTRAINT pk_FosterHome PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Admin
ADD 
CONSTRAINT pk_Admin PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Email
ADD 
CONSTRAINT pk_Email PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Phone
ADD 
CONSTRAINT pk_Phone PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE BlockList
ADD 
CONSTRAINT pk_BlockList PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Association
ADD 
CONSTRAINT pk_Association PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Deleted
ADD 
CONSTRAINT pk_Deleted PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Created
ADD 
CONSTRAINT pk_Created PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Parameter
ADD 
CONSTRAINT pk_Parameter PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Bitacora
ADD 
CONSTRAINT pk_Bitacora PRIMARY KEY (Id)
USING INDEX
TABLESPACE BIENESTAR_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);