ALTER TABLE PetLevelEnergy
ADD
CONSTRAINT pk_PetLevelEnergy PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetBreed
ADD CONSTRAINT pk_PetBreed PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetType
ADD CONSTRAINT pk_PetType PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetState
ADD CONSTRAINT pk_PetState PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetIllness
ADD CONSTRAINT pk_PetIllness PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Medicine
ADD CONSTRAINT pk_Medicine PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetTreatment
ADD CONSTRAINT pk_PetTreatment PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetTraining
ADD CONSTRAINT pk_PetTraining PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetPhoto
ADD CONSTRAINT pk_PetPhoto PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SpaceRequired
ADD CONSTRAINT pk_SpaceRequired PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetSize
ADD CONSTRAINT pk_PetSize PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE District
ADD CONSTRAINT pk_District PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Canton
ADD CONSTRAINT pk_Canton PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Province
ADD CONSTRAINT pk_Province PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Country
ADD CONSTRAINT pk_Country PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetSeverity
ADD CONSTRAINT pk_PetSeverity PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Pet
ADD CONSTRAINT pk_Pet PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Veterinarian
ADD CONSTRAINT pk_Veterinarian PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetSizeXFosterHome
ADD CONSTRAINT pk_PetSizeXFosterHome PRIMARY KEY (IdPetSize, IdFosterHome)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXPetTreatment
ADD CONSTRAINT pk_PetXPetTreatment PRIMARY KEY (IdPet, IdPetTreatment)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXPetIllness
ADD CONSTRAINT pk_PetXPetIllness PRIMARY KEY (IdPet, IdPetIllness)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetXMedicine
ADD CONSTRAINT pk_PetXMedicine PRIMARY KEY (IdPet, IdMedicine)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetLevelEnergyXFosterHome
ADD CONSTRAINT pk_PetLevelEnergyXFosterHome PRIMARY KEY (IdPetLevelEnergy, IdFosterHome)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE SpaceRequiredXFosterHome
ADD CONSTRAINT pk_SpaceRequiredXFosterHome PRIMARY KEY (IdSpaceRequired, IdFosterHome)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE FoundReport
ADD CONSTRAINT pk_FoundReport PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE PetMatch
ADD CONSTRAINT pk_Match PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE LostReport
ADD CONSTRAINT pk_LostReport PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Adoption
ADD CONSTRAINT pk_Adoption PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Rescued
ADD CONSTRAINT pk_Rescued PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Donation
ADD CONSTRAINT pk_Donation PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Currency
ADD CONSTRAINT pk_Currency PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Person
ADD CONSTRAINT pk_Person PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE ReportList
ADD CONSTRAINT pk_ReportList PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Rescuer
ADD CONSTRAINT pk_Rescuer PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Adopter
ADD CONSTRAINT pk_Adopter PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Calification
ADD CONSTRAINT pk_Calification PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE FosterHome
ADD CONSTRAINT pk_FosterHome PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Admin
ADD CONSTRAINT pk_Admin PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Email
ADD CONSTRAINT pk_Email PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Phone
ADD CONSTRAINT pk_Phone PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE BlockList
ADD CONSTRAINT pk_BlockList PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Association
ADD CONSTRAINT pk_Association PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Deleted
ADD CONSTRAINT pk_Deleted PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Created
ADD CONSTRAINT pk_Created PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Parameter
ADD CONSTRAINT pk_Parameter PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);

ALTER TABLE Bitacora
ADD CONSTRAINT pk_Bitacora PRIMARY KEY (Id)
USING INDEX
TABLESPACE WELFARE_INDICE PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);


-- secuencias para generar los ids de las tablas
CREATE SEQUENCE s_PetLevelEnergy START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetBreed START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetType START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetState START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetIllness START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Medicine START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetTreatment START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetTraining START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetPhoto START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_SpaceRequired START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetSize START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_District START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Canton START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Province START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Country START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetSeverity START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Pet START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Veterinarian START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_FoundReport START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_PetMatch START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_LostReport START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Adoption START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Rescued START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Donation START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Currency START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Person START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_ReportList START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Rescuer START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Adopter START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Calification START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_FosterHome START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Admin START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Email START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Phone START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_BlockList START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Association START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Deleted START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Created START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Parameter START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE s_Bitacora START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;