CREATE TABLESPACE WELFARE_INDICE
DATAFILE 'C:\Users\carlo\OneDrive\Escritorio\Laboratorio 1\WELFARE_INDICE.dbf' -- esto lo adaptan a su ruta
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE TABLESPACE WELFARE_DATA
DATAFILE 'C:\Users\carlo\OneDrive\Escritorio\Laboratorio 1\WELFARE_DATA.dbf' -- esto lo adaptan a su ruta
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE USER WELFARE
IDENTIFIED BY welfare123
DEFAULT TABLESPACE WELFARE_DATA
QUOTA 10M ON WELFARE_DATA
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO WELFARE;
GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW TO WELFARE;
ALTER USER WELFARE QUOTA UNLIMITED ON WELFARE_INDICE;


