CREATE TABLESPACE BIENESTAR_INDICE
DATAFILE 'C:\Users\carlo\OneDrive\Escritorio\Laboratorio 1\BIENESTAR_INDICE.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE TABLESPACE BIENESTAR_DATA
DATAFILE 'C:\Users\carlo\OneDrive\Escritorio\Laboratorio 1\BIENESTAR_DATA.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE USER BIENESTAR
IDENTIFIED BY bienestar123
DEFAULT TABLESPACE BIENESTAR_DATA
QUOTA 10M ON BIENESTAR_DATA
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;

GRANT CONNECT, CREATE SESSION, CREATE TABLE TO BIENESTAR;