CREATE SEQUENCE Seq_AuditDeleted
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER Trg_AuditDeleted_BI
BEFORE INSERT ON AuditDeleted
FOR EACH ROW
BEGIN
    IF :NEW.Id IS NULL THEN
        SELECT Seq_AuditDeleted.NEXTVAL
        INTO :NEW.Id
        FROM Dual;
    END IF;
END;
/

CREATE SEQUENCE Seq_AuditCreated
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER Trg_AuditCreated_BI
BEFORE INSERT ON AuditCreated
FOR EACH ROW
BEGIN
    IF :NEW.Id IS NULL THEN
        SELECT Seq_AuditCreated.NEXTVAL
        INTO :NEW.Id
        FROM Dual;
    END IF;
END;
/

CREATE SEQUENCE Seq_SystemParameter
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER Trg_SystemParameter_BI
BEFORE INSERT ON SystemParameter
FOR EACH ROW
BEGIN
    IF :NEW.Id IS NULL THEN
        SELECT Seq_SystemParameter.NEXTVAL
        INTO :NEW.Id
        FROM Dual;
    END IF;
END;
/

CREATE SEQUENCE Seq_Bitacora
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER Trg_Bitacora_BI
BEFORE INSERT ON Bitacora
FOR EACH ROW
BEGIN
    IF :NEW.Id IS NULL THEN
        SELECT Seq_Bitacora.NEXTVAL
        INTO :NEW.Id
        FROM Dual;
    END IF;
END;
/