package animalwelfare.userInterface;


public class EnterEmail extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public EnterEmail() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        TextEmail = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonContinue = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        LabelField1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LabelField2 = new javax.swing.JLabel();
        LabelField3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));

        PanelForm.setBackground(new java.awt.Color(255, 255, 255));

        TextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextEmail.setBorder(null);
        TextEmail.addActionListener(this::TextEmailActionPerformed);

        LabelField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField.setText("Enter your Password");

        ButtonContinue.setBackground(new java.awt.Color(255, 216, 20));
        ButtonContinue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonContinue.setText("Continue");
        ButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonContinue.addActionListener(this::ButtonContinueActionPerformed);

        LableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LableTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LableTitle.setText("Animal Welfare");

        LabelField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField1.setText("Enter your User Name");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(null);

        LabelField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField2.setText("______________________________________________________________________________");
        LabelField2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LabelField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField3.setText("______________________________________________________________________________");
        LabelField3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/banner_image.jpg"))); // NOI18N

        ButtonCreateAccount.setBackground(new java.awt.Color(255, 255, 254));
        ButtonCreateAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonCreateAccount.setText("Create Account");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelField3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelField2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelField1)
                    .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelField)
                    .addComponent(TextEmail)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LableTitle)
                .addGap(59, 59, 59)
                .addComponent(LabelField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelField3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelField2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelBackGroundLayout = new javax.swing.GroupLayout(PanelBackGround);
        PanelBackGround.setLayout(PanelBackGroundLayout);
        PanelBackGroundLayout.setHorizontalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBackGroundLayout.setVerticalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void ButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContinueActionPerformed

    }//GEN-LAST:event_ButtonContinueActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        SignUpForm window = new SignUpForm();
        dispose();
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContinue;
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelField1;
    private javax.swing.JLabel LabelField2;
    private javax.swing.JLabel LabelField3;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
