/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;
import animalwelfare.access.DbObject;
import animalwelfare.business.InsertPetController;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
/**
 *
 * @author valer
 */
public class InsertPetForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InsertPetForm.class.getName());


    // controlador del formulario
    private InsertPetController controller = null;

    // procedimiento que rellena el combobox de Veterinarian
    public void fillVeterinarian(ArrayList<DbObject> listVeterinarian) {
        ComboVeterinarianPet.removeAllItems();
        ComboVeterinarianPet.addItem(new DbObject(0,"-"));
        for (DbObject c : listVeterinarian) {
            ComboVeterinarianPet.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Breed
    public void fillPetBreed(ArrayList<DbObject> listBreed) {
        ComboBreedPet.removeAllItems();
        ComboBreedPet.addItem(new DbObject(0,"-"));
        for (DbObject c : listBreed) {
            ComboBreedPet.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Size
    public void fillPetSize(ArrayList<DbObject> listSize) {
        ComboSizePet.removeAllItems();
        ComboSizePet.addItem(new DbObject(0,"-"));
        for (DbObject c : listSize) {
            ComboSizePet.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Energy
    public void fillPetEnergy(ArrayList<DbObject> listEnergy) {
        ComboEnergyPet.removeAllItems();
        ComboEnergyPet.addItem(new DbObject(0,"-"));
        for (DbObject c : listEnergy) {
            ComboEnergyPet.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Space Requiered
    public void fillPetSpaceRequired(ArrayList<DbObject> listSpaceRequiered) {
        ComboSpaceRequieredPet.removeAllItems();
        ComboSpaceRequieredPet.addItem(new DbObject(0,"-"));
        for (DbObject c : listSpaceRequiered) {
            ComboSpaceRequieredPet.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Pet trainig
    public void fillPetTraining(ArrayList<DbObject> listPetTraining) {
        ComboPetTraining.removeAllItems();
        ComboPetTraining.addItem(new DbObject(0,"-"));
        for (DbObject c : listPetTraining) {
            ComboPetTraining.addItem(c);
        }
    }

    // procedimiento que rellena el combobox de Pet Type
    public void fillPetType(ArrayList<DbObject> listPetType) {
        ComboPetType.removeAllItems();
        ComboPetType.addItem(new DbObject(0,"-"));
        for (DbObject c : listPetType) {
            ComboPetType.addItem(c);
        }
    }

    

    // procedimiento que rellena el combobox de Country
    public void fillCountry(ArrayList<DbObject> listCountry) {
        ComboCountry.removeAllItems();
        ComboCountry.addItem(new DbObject(0,"-"));
        for (DbObject c : listCountry) {
            ComboCountry.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Province
    public void fillProvince(ArrayList<DbObject> listProvince) {
        ComboProvince.removeAllItems();
        ComboProvince.addItem(new DbObject(0,"-"));
        for (DbObject c : listProvince) {
            ComboProvince.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Canton
    public void fillCanton(ArrayList<DbObject> listCanton) {
        ComboCanton.removeAllItems();
        ComboCanton.addItem(new DbObject(0,"-"));
        for (DbObject c : listCanton) {
            ComboCanton.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de District
    public void fillDistrict(ArrayList<DbObject> listDistrict) {
        ComboDistrict.removeAllItems();
        ComboDistrict.addItem(new DbObject(0,"-"));
        for (DbObject c : listDistrict) {
            ComboDistrict.addItem(c);
        }
    }

    public InsertPetForm() {
        initComponents(); // Inicializar los componentes del formulario
        setLocationRelativeTo(null); // Centrar el formulario en la pantalla

        controller = new InsertPetController(this);

        ComboProvince.setEnabled(false);
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);

        setVisible(true); // Hacer visible el formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelSubTitle = new javax.swing.JLabel();
        TextPetName = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();
        TextColorPet = new javax.swing.JTextField();
        LabelField1 = new javax.swing.JLabel();
        LabelField2 = new javax.swing.JLabel();
        ComboVeterinarianPet = new javax.swing.JComboBox<>();
        LabelCountry = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelField4 = new javax.swing.JLabel();
        LabelField5 = new javax.swing.JLabel();
        TextChipNumber = new javax.swing.JTextField();
        LabelField6 = new javax.swing.JLabel();
        ComboSizePet = new javax.swing.JComboBox<>();
        LabelField7 = new javax.swing.JLabel();
        ComboEnergyPet = new javax.swing.JComboBox<>();
        LabelField8 = new javax.swing.JLabel();
        LabelCountry1 = new javax.swing.JLabel();
        ComboCountry = new javax.swing.JComboBox<>();
        LabelProvince = new javax.swing.JLabel();
        ComboProvince = new javax.swing.JComboBox<>();
        LabelCanton = new javax.swing.JLabel();
        ComboCanton = new javax.swing.JComboBox<>();
        LabelDistrict = new javax.swing.JLabel();
        ComboDistrict = new javax.swing.JComboBox<>();
        LabelField9 = new javax.swing.JLabel();
        ComboPetTraining = new javax.swing.JComboBox<>();
        ComboBreedPet = new javax.swing.JComboBox<>();
        ComboAgePet = new javax.swing.JComboBox<>();
        ComboSpaceRequieredPet = new javax.swing.JComboBox<>();
        ComboPetType = new javax.swing.JComboBox<>();
        LabelField3 = new javax.swing.JLabel();
        LableTitle = new javax.swing.JLabel();
        ImagenBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));
        PanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Veterinarian information");

        LabelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTitle.setText("Register Pet");

        TextPetName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPetName.addActionListener(this::TextPetNameActionPerformed);

        LabelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField.setText("Pet Name");

        ButtonCreateAccount.setBackground(new java.awt.Color(255, 216, 20));
        ButtonCreateAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonCreateAccount.setText("Register Pet");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);

        TextColorPet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextColorPet.setToolTipText("");
        TextColorPet.addActionListener(this::TextColorPetActionPerformed);

        LabelField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField1.setText("Color");

        LabelField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField2.setText("Trainig level");

        ComboVeterinarianPet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboVeterinarianPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboVeterinarianPet.setOpaque(true);
        ComboVeterinarianPet.setRequestFocusEnabled(false);
        ComboVeterinarianPet.addActionListener(this::ComboVeterinarianPetActionPerformed);

        LabelCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCountry.setText("Select a Registered Veterinarian");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("___________________________________________________________________________________________________");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LabelField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField4.setText("Age");

        LabelField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField5.setText("Size");

        TextChipNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextChipNumber.addActionListener(this::TextChipNumberActionPerformed);

        LabelField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField6.setText("Chip Number (Optional)");

        ComboSizePet.setBackground(new java.awt.Color(254, 254, 254));
        ComboSizePet.addActionListener(this::ComboSizePetActionPerformed);

        LabelField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField7.setText("Space Requiered");

        ComboEnergyPet.setBackground(new java.awt.Color(254, 254, 254));
        ComboEnergyPet.addActionListener(this::ComboEnergyPetActionPerformed);

        LabelField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField8.setText("Energy of the pet");

        LabelCountry1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCountry1.setText("Country");

        ComboCountry.setBackground(new java.awt.Color(254, 254, 254));
        ComboCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCountry.setOpaque(true);
        ComboCountry.setRequestFocusEnabled(false);
        ComboCountry.addActionListener(this::ComboCountryActionPerformed);

        LabelProvince.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelProvince.setText("Province");

        ComboProvince.setBackground(new java.awt.Color(254, 254, 254));
        ComboProvince.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProvince.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboProvince.setOpaque(true);
        ComboProvince.setRequestFocusEnabled(false);
        ComboProvince.addActionListener(this::ComboProvinceActionPerformed);

        LabelCanton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCanton.setText("Canton");

        ComboCanton.setBackground(new java.awt.Color(254, 254, 254));
        ComboCanton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCanton.setOpaque(true);
        ComboCanton.setRequestFocusEnabled(false);
        ComboCanton.addActionListener(this::ComboCantonActionPerformed);

        LabelDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelDistrict.setText("District");

        ComboDistrict.setBackground(new java.awt.Color(254, 254, 254));
        ComboDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboDistrict.setOpaque(true);
        ComboDistrict.setRequestFocusEnabled(false);
        ComboDistrict.addActionListener(this::ComboDistrictActionPerformed);

        LabelField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField9.setText("Breed(Optional)");

        ComboPetTraining.setBackground(new java.awt.Color(254, 254, 254));
        ComboPetTraining.addActionListener(this::ComboPetTrainingActionPerformed);

        ComboBreedPet.setBackground(new java.awt.Color(254, 254, 254));

        ComboAgePet.setBackground(new java.awt.Color(254, 254, 254));
        ComboAgePet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", " " }));

        ComboSpaceRequieredPet.setBackground(new java.awt.Color(254, 254, 254));
        ComboSpaceRequieredPet.addActionListener(this::ComboSpaceRequieredPetActionPerformed);

        ComboPetType.setBackground(new java.awt.Color(254, 254, 254));
        ComboPetType.addActionListener(this::ComboPetTypeActionPerformed);

        LabelField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField3.setText("Species");

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboVeterinarianPet, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelCountry)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(20, 20, 20))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(PanelFormLayout.createSequentialGroup()
                                                    .addComponent(LabelField5)
                                                    .addGap(191, 191, 191))
                                                .addGroup(PanelFormLayout.createSequentialGroup()
                                                    .addComponent(ComboSizePet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addComponent(LabelField4)
                                                .addGap(190, 190, 190)))
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelField8)
                                            .addComponent(ComboEnergyPet, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCountry1)))
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelField1)
                                            .addComponent(TextPetName, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(TextColorPet))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboPetType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TextChipNumber)
                                                        .addComponent(LabelField6, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                                    .addComponent(LabelField3))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(LabelField))
                                .addGap(18, 18, 18)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboBreedPet, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboPetTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelField2))
                                        .addGap(0, 28, Short.MAX_VALUE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelField7)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(ComboSpaceRequieredPet, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(ComboAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelCanton)
                                            .addComponent(ComboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(24, 24, 24)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelDistrict)
                                    .addComponent(ComboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelProvince))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubTitle)
                .addGap(18, 18, 18)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField)
                    .addComponent(LabelField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelField9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextChipNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBreedPet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField1)
                    .addComponent(LabelField2)
                    .addComponent(LabelField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextColorPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboPetType)
                    .addComponent(ComboPetTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField5)
                    .addComponent(LabelField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboSizePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboEnergyPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField4)
                    .addComponent(LabelCountry1)
                    .addComponent(LabelProvince))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField7)
                    .addComponent(LabelCanton)
                    .addComponent(LabelDistrict))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboSpaceRequieredPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LabelCountry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboVeterinarianPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCreateAccount)
                .addGap(92, 92, 92))
        );

        PanelBackGround.add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 730, 590));

        LableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 255, 255));
        LableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle.setText("Animal Welfare");
        PanelBackGround.add(LableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 730, -1));

        ImagenBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/BackgroundCat.jpg"))); // NOI18N
        PanelBackGround.add(ImagenBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void TextPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPetNameActionPerformed

    private void TextColorPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextColorPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextColorPetActionPerformed

    private void TextChipNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextChipNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextChipNumberActionPerformed

    private void ComboSizePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSizePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSizePetActionPerformed

    private void ComboEnergyPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEnergyPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEnergyPetActionPerformed

    private void ComboVeterinarianPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVeterinarianPetActionPerformed

    }//GEN-LAST:event_ComboVeterinarianPetActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    private void ComboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCountryActionPerformed
        // al seleccionar un pais, se llena el de province y se bloquea los siguientes.
        if (controller == null) return;
        DbObject country = (DbObject) ComboCountry.getSelectedItem();
        if (country == null) return;
        if (country.getId() == 0) return;
        ComboCanton.removeAllItems();
        ComboDistrict.removeAllItems();
        
        controller.FillProvince(this, country.getId());
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);
        ComboProvince.setEnabled(true);
    }//GEN-LAST:event_ComboCountryActionPerformed

    private void ComboProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvinceActionPerformed
        // al seleccionar una provincia, se llena el de canton y se bloquea los siguientes.
        DbObject province = (DbObject) ComboProvince.getSelectedItem();
        if (province == null) return;
        if (province.getId() == 0) return;
        ComboDistrict.removeAllItems();
        
        controller.FillCanton(this, province.getId());
        ComboDistrict.setEnabled(false);
        ComboCanton.setEnabled(true);
    }//GEN-LAST:event_ComboProvinceActionPerformed

    private void ComboCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCantonActionPerformed
        // al seleccionar un canton, se llena el de Distrito.
        DbObject canton = (DbObject) ComboCanton.getSelectedItem();
        if (canton == null) return;
        if (canton.getId() == 0) return;
        ComboDistrict.removeAllItems();
        
        controller.FillDistrict(this, canton.getId());
        ComboDistrict.setEnabled(true);
    }//GEN-LAST:event_ComboCantonActionPerformed

    private void ComboPetTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPetTrainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPetTrainingActionPerformed

    private void ComboSpaceRequieredPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSpaceRequieredPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSpaceRequieredPetActionPerformed

    private void ComboDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDistrictActionPerformed

    private void ComboPetTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPetTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPetTypeActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InsertPetForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JComboBox<String> ComboAgePet;
    private javax.swing.JComboBox<DbObject> ComboBreedPet;
    private javax.swing.JComboBox<DbObject> ComboCanton;
    private javax.swing.JComboBox<DbObject> ComboCountry;
    private javax.swing.JComboBox<DbObject> ComboDistrict;
    private javax.swing.JComboBox<DbObject> ComboEnergyPet;
    private javax.swing.JComboBox<DbObject> ComboPetTraining;
    private javax.swing.JComboBox<DbObject> ComboPetType;
    private javax.swing.JComboBox<DbObject> ComboProvince;
    private javax.swing.JComboBox<DbObject> ComboSizePet;
    private javax.swing.JComboBox<DbObject> ComboSpaceRequieredPet;
    private javax.swing.JComboBox<DbObject> ComboVeterinarianPet;
    private javax.swing.JLabel ImagenBackGround;
    private javax.swing.JLabel LabelCanton;
    private javax.swing.JLabel LabelCountry;
    private javax.swing.JLabel LabelCountry1;
    private javax.swing.JLabel LabelDistrict;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelField1;
    private javax.swing.JLabel LabelField2;
    private javax.swing.JLabel LabelField3;
    private javax.swing.JLabel LabelField4;
    private javax.swing.JLabel LabelField5;
    private javax.swing.JLabel LabelField6;
    private javax.swing.JLabel LabelField7;
    private javax.swing.JLabel LabelField8;
    private javax.swing.JLabel LabelField9;
    private javax.swing.JLabel LabelProvince;
    private javax.swing.JLabel LabelSubTitle;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JTextField TextChipNumber;
    private javax.swing.JTextField TextColorPet;
    private javax.swing.JTextField TextPetName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
