/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import animalwelfare.security.Session;


/**
 *
 * @author carlo
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    // controlador
    //private MainMenuController controller = null;
    
    // constante
    Color buttonHover = new Color(220, 220, 220);
    Color buttonBase = new Color(242, 242, 242);
    
    
    private int currentUserId;

    public MainMenu() {
        this(Session.getInstance().getUserId());
    }

    public MainMenu(int currentUserId) {
        initComponents();
        this.currentUserId = currentUserId;

        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    private void LogOffButtonMouseEntered(java.awt.event.MouseEvent evt) {
        LogOffButton.setBackground(buttonHover);
    }
    private void LogOffButtonMouseExited(java.awt.event.MouseEvent evt) {
        LogOffButton.setBackground(buttonBase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BackGround = new javax.swing.JPanel();
        PetsButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Banner = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NewPetButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DonationsButton = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        RescuesButton = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        StatsButton = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        LableTitle = new javax.swing.JLabel();
        LogOffButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        FosterHomeButton = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        BlockListButton = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(0, 102, 102));

        PetsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PetsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PetsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PetsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PetsButtonMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Pets");

        javax.swing.GroupLayout PetsButtonLayout = new javax.swing.GroupLayout(PetsButton);
        PetsButton.setLayout(PetsButtonLayout);
        PetsButtonLayout.setHorizontalGroup(
            PetsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetsButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        PetsButtonLayout.setVerticalGroup(
            PetsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Banner.setBackground(new java.awt.Color(0, 121, 121));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/istockphoto-2184260648-612x612.jpg"))); // NOI18N

        javax.swing.GroupLayout BannerLayout = new javax.swing.GroupLayout(Banner);
        Banner.setLayout(BannerLayout);
        BannerLayout.setHorizontalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );
        BannerLayout.setVerticalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        NewPetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewPetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPetButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewPetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewPetButtonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("New Pet");

        javax.swing.GroupLayout NewPetButtonLayout = new javax.swing.GroupLayout(NewPetButton);
        NewPetButton.setLayout(NewPetButtonLayout);
        NewPetButtonLayout.setHorizontalGroup(
            NewPetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPetButtonLayout.createSequentialGroup()
                .addContainerGap()
<<<<<<< Updated upstream
                .addGroup(NewPetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
=======
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        NewPetButtonLayout.setVerticalGroup(
            NewPetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DonationsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DonationsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonationsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DonationsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DonationsButtonMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Donations");

        javax.swing.GroupLayout DonationsButtonLayout = new javax.swing.GroupLayout(DonationsButton);
        DonationsButton.setLayout(DonationsButtonLayout);
        DonationsButtonLayout.setHorizontalGroup(
            DonationsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonationsButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DonationsButtonLayout.setVerticalGroup(
            DonationsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        RescuesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RescuesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RescuesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RescuesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RescuesButtonMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Match");

        javax.swing.GroupLayout RescuesButtonLayout = new javax.swing.GroupLayout(RescuesButton);
        RescuesButton.setLayout(RescuesButtonLayout);
        RescuesButtonLayout.setHorizontalGroup(
            RescuesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RescuesButtonLayout.createSequentialGroup()
                .addContainerGap()
<<<<<<< Updated upstream
                .addGroup(RescuesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        RescuesButtonLayout.setVerticalGroup(
            RescuesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        StatsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StatsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatsButtonMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Stats");

        javax.swing.GroupLayout StatsButtonLayout = new javax.swing.GroupLayout(StatsButton);
        StatsButton.setLayout(StatsButtonLayout);
        StatsButtonLayout.setHorizontalGroup(
            StatsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsButtonLayout.createSequentialGroup()
                .addContainerGap()
<<<<<<< Updated upstream
                .addGroup(StatsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
=======
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> Stashed changes
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatsButtonLayout.setVerticalGroup(
            StatsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsButtonLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< Updated upstream
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
=======
>>>>>>> Stashed changes
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LableTitle.setFont(new java.awt.Font("Roboto SemiBold", 0, 36)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(242, 242, 242));
        LableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle.setText("WELCOME!");

        LogOffButton.setBackground(new java.awt.Color(255, 204, 51));
        LogOffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOffButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOffButtonMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("EXIT");

        javax.swing.GroupLayout LogOffButtonLayout = new javax.swing.GroupLayout(LogOffButton);
        LogOffButton.setLayout(LogOffButtonLayout);
        LogOffButtonLayout.setHorizontalGroup(
            LogOffButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOffButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        LogOffButtonLayout.setVerticalGroup(
            LogOffButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOffButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        FosterHomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FosterHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FosterHomeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FosterHomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FosterHomeButtonMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Foster Home");

<<<<<<< Updated upstream
        jLabel25.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel25.setText("Give a pet a safe temporary home");

=======
>>>>>>> Stashed changes
        javax.swing.GroupLayout FosterHomeButtonLayout = new javax.swing.GroupLayout(FosterHomeButton);
        FosterHomeButton.setLayout(FosterHomeButtonLayout);
        FosterHomeButtonLayout.setHorizontalGroup(
            FosterHomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FosterHomeButtonLayout.createSequentialGroup()
                .addContainerGap()
<<<<<<< Updated upstream
                .addGroup(FosterHomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        FosterHomeButtonLayout.setVerticalGroup(
            FosterHomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FosterHomeButtonLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
=======
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FosterHomeButtonLayout.setVerticalGroup(
            FosterHomeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BlockListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BlockListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockListButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockListButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockListButtonMouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Blocklist");

        javax.swing.GroupLayout BlockListButtonLayout = new javax.swing.GroupLayout(BlockListButton);
        BlockListButton.setLayout(BlockListButtonLayout);
        BlockListButtonLayout.setHorizontalGroup(
            BlockListButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlockListButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        BlockListButtonLayout.setVerticalGroup(
            BlockListButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DonationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RescuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PetsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< Updated upstream
                            .addComponent(NewPetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DonationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FosterHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
=======
                            .addComponent(NewPetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FosterHomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addComponent(BlockListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(LogOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
<<<<<<< Updated upstream
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addGap(33, 33, 33))
>>>>>>> Stashed changes
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< Updated upstream
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(PetsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(NewPetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(DonationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(StatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RescuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FosterHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
=======
                .addGap(18, 18, 18)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(LableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(LogOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PetsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlockListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DonationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RescuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FosterHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
>>>>>>> Stashed changes
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsButtonMouseEntered
        PetsButton.setBackground(buttonHover);
    }//GEN-LAST:event_PetsButtonMouseEntered

    private void PetsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsButtonMouseExited
        PetsButton.setBackground(buttonBase);
    }//GEN-LAST:event_PetsButtonMouseExited

    private void NewPetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPetButtonMouseEntered
        NewPetButton.setBackground(buttonHover);
    }//GEN-LAST:event_NewPetButtonMouseEntered

    private void NewPetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPetButtonMouseExited
        NewPetButton.setBackground(buttonBase);
    }//GEN-LAST:event_NewPetButtonMouseExited

    private void RescuesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RescuesButtonMouseEntered
        RescuesButton.setBackground(buttonHover);
    }//GEN-LAST:event_RescuesButtonMouseEntered

    private void RescuesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RescuesButtonMouseExited
        RescuesButton.setBackground(buttonBase);
    }//GEN-LAST:event_RescuesButtonMouseExited

    private void DonationsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonationsButtonMouseEntered
        DonationsButton.setBackground(buttonHover);
    }//GEN-LAST:event_DonationsButtonMouseEntered

    private void DonationsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonationsButtonMouseExited
        DonationsButton.setBackground(buttonBase);
    }//GEN-LAST:event_DonationsButtonMouseExited

    private void StatsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsButtonMouseEntered
        StatsButton.setBackground(buttonHover);
    }//GEN-LAST:event_StatsButtonMouseEntered

    private void StatsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsButtonMouseExited
        StatsButton.setBackground(buttonBase);
    }//GEN-LAST:event_StatsButtonMouseExited

    private void PetsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsButtonMouseClicked
        UserPetTable window = new UserPetTable(currentUserId);
        dispose();
    }//GEN-LAST:event_PetsButtonMouseClicked

    private void RescuesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RescuesButtonMouseClicked
        InsertPetForm window = new InsertPetForm();
        dispose();
    }//GEN-LAST:event_RescuesButtonMouseClicked

    private void NewPetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPetButtonMouseClicked
        InsertPetForm window = new InsertPetForm();
        dispose();
    }//GEN-LAST:event_NewPetButtonMouseClicked

    private void DonationsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonationsButtonMouseClicked
        DonationForm window = new DonationForm();
        dispose();
    }//GEN-LAST:event_DonationsButtonMouseClicked

    private void FosterHomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FosterHomeButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FosterHomeButtonMouseEntered

    private void FosterHomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FosterHomeButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FosterHomeButtonMouseExited

    private void FosterHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FosterHomeButtonMouseClicked
        FosterHomeForm window = new FosterHomeForm();
        dispose();
    }//GEN-LAST:event_FosterHomeButtonMouseClicked

    private void BlockListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockListButtonMouseClicked
        BlockListForm window = new BlockListForm();
        dispose();
    }//GEN-LAST:event_BlockListButtonMouseClicked

    private void BlockListButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockListButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BlockListButtonMouseEntered

    private void BlockListButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockListButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BlockListButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Banner;
    private javax.swing.JPanel BlockListButton;
    private javax.swing.JPanel DonationsButton;
    private javax.swing.JPanel FosterHomeButton;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel LogOffButton;
    private javax.swing.JPanel NewPetButton;
    private javax.swing.JPanel PetsButton;
    private javax.swing.JPanel RescuesButton;
    private javax.swing.JPanel StatsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
