/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;

import animalwelfare.access.DbObject;


/**
 *
 * @author valer
 */
public class RegisterVeterinarian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterVeterinarian.class.getName());

    /**
     * Creates new form RegisterVeterinarian
     */
    public RegisterVeterinarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TextVetLoctaion = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ComboDistrict3 = new javax.swing.JComboBox<>();
        LabelDistrict3 = new javax.swing.JLabel();
        ComboCanton3 = new javax.swing.JComboBox<>();
        LabelCanton3 = new javax.swing.JLabel();
        ComboProvince3 = new javax.swing.JComboBox<>();
        LabelProvince3 = new javax.swing.JLabel();
        ComboCountry3 = new javax.swing.JComboBox<>();
        LabelCountry3 = new javax.swing.JLabel();
        TextPhoneVet = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TextVetClinicName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TextVetLastName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TextVetFirstName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVetLoctaion.addActionListener(this::TextVetLoctaionActionPerformed);
        jPanel2.add(TextVetLoctaion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 600, 100));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Location");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 30));

        ComboDistrict3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboDistrict3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboDistrict3.setOpaque(true);
        ComboDistrict3.setRequestFocusEnabled(false);
        jPanel2.add(ComboDistrict3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, -1));

        LabelDistrict3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelDistrict3.setText("District");
        jPanel2.add(LabelDistrict3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, -1));

        ComboCanton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCanton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCanton3.setOpaque(true);
        ComboCanton3.setRequestFocusEnabled(false);
        ComboCanton3.addActionListener(this::ComboCanton3ActionPerformed);
        jPanel2.add(ComboCanton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 180, -1));

        LabelCanton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCanton3.setText("Canton");
        jPanel2.add(LabelCanton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        ComboProvince3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProvince3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboProvince3.setOpaque(true);
        ComboProvince3.setRequestFocusEnabled(false);
        ComboProvince3.addActionListener(this::ComboProvince3ActionPerformed);
        jPanel2.add(ComboProvince3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 180, -1));

        LabelProvince3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelProvince3.setText("Province");
        jPanel2.add(LabelProvince3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        ComboCountry3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCountry3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCountry3.setOpaque(true);
        ComboCountry3.setRequestFocusEnabled(false);
        ComboCountry3.addActionListener(this::ComboCountry3ActionPerformed);
        jPanel2.add(ComboCountry3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        LabelCountry3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCountry3.setText("Country");
        jPanel2.add(LabelCountry3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel2.add(TextPhoneVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Phone");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, 30));
        jPanel2.add(TextVetClinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Clinic's Name");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));
        jPanel2.add(TextVetLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Last Name");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, 30));
        jPanel2.add(TextVetFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("First Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 630, 420));

        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setText("Register Veterinarian");
        jLabel24.setOpaque(true);
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 40));

        jLabel9.setBackground(new java.awt.Color(204, 204, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/Cat1.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 840, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCountry3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCountry3ActionPerformed

    }//GEN-LAST:event_ComboCountry3ActionPerformed

    private void ComboProvince3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvince3ActionPerformed

    }//GEN-LAST:event_ComboProvince3ActionPerformed

    private void ComboCanton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCanton3ActionPerformed

    }//GEN-LAST:event_ComboCanton3ActionPerformed

    private void TextVetLoctaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVetLoctaionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVetLoctaionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterVeterinarian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<DbObject> ComboCanton3;
    private javax.swing.JComboBox<DbObject> ComboCountry3;
    private javax.swing.JComboBox<DbObject> ComboDistrict3;
    private javax.swing.JComboBox<DbObject> ComboProvince3;
    private javax.swing.JLabel LabelCanton3;
    private javax.swing.JLabel LabelCountry3;
    private javax.swing.JLabel LabelDistrict3;
    private javax.swing.JLabel LabelProvince3;
    private javax.swing.JTextField TextPhoneVet;
    private javax.swing.JTextField TextVetClinicName;
    private javax.swing.JTextField TextVetFirstName;
    private javax.swing.JTextField TextVetLastName;
    private javax.swing.JTextField TextVetLoctaion;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
