/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;

import animalwelfare.access.DbObject;


/**
 *
 * @author valer
 */
public class RegisterVeterinarian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterVeterinarian.class.getName());

    /**
     * Creates new form RegisterVeterinarian
     */
    public RegisterVeterinarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextVetLoctaion = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ComboDistrict = new javax.swing.JComboBox<>();
        LabelDistrict3 = new javax.swing.JLabel();
        ComboCanton3 = new javax.swing.JComboBox<>();
        LabelCanton3 = new javax.swing.JLabel();
        ComboProvince3 = new javax.swing.JComboBox<>();
        LabelProvince3 = new javax.swing.JLabel();
        ComboCountry3 = new javax.swing.JComboBox<>();
        LabelCountry3 = new javax.swing.JLabel();
        TextPhoneVet = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TextVetClinicName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TextVetLastName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TextVetFirstName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("_________________________________________________________________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        TextVetLoctaion.addActionListener(this::TextVetLoctaionActionPerformed);
        jPanel2.add(TextVetLoctaion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 450, 60));

        jLabel29.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 153));
        jLabel29.setText("Address");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 90, 30));

        ComboDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboDistrict.setOpaque(true);
        ComboDistrict.setRequestFocusEnabled(false);
        jPanel2.add(ComboDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));

        LabelDistrict3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        LabelDistrict3.setForeground(new java.awt.Color(0, 153, 153));
        LabelDistrict3.setText("District");
        jPanel2.add(LabelDistrict3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, -1));

        ComboCanton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCanton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCanton3.setOpaque(true);
        ComboCanton3.setRequestFocusEnabled(false);
        ComboCanton3.addActionListener(this::ComboCanton3ActionPerformed);
        jPanel2.add(ComboCanton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, -1));

        LabelCanton3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        LabelCanton3.setForeground(new java.awt.Color(0, 153, 153));
        LabelCanton3.setText("Canton");
        jPanel2.add(LabelCanton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        ComboProvince3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProvince3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboProvince3.setOpaque(true);
        ComboProvince3.setRequestFocusEnabled(false);
        ComboProvince3.addActionListener(this::ComboProvince3ActionPerformed);
        jPanel2.add(ComboProvince3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 180, -1));

        LabelProvince3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        LabelProvince3.setForeground(new java.awt.Color(0, 153, 153));
        LabelProvince3.setText("Province");
        jPanel2.add(LabelProvince3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        ComboCountry3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCountry3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCountry3.setOpaque(true);
        ComboCountry3.setRequestFocusEnabled(false);
        ComboCountry3.addActionListener(this::ComboCountry3ActionPerformed);
        jPanel2.add(ComboCountry3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 180, -1));

        LabelCountry3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        LabelCountry3.setForeground(new java.awt.Color(0, 153, 153));
        LabelCountry3.setText("Country");
        jPanel2.add(LabelCountry3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jPanel2.add(TextPhoneVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 180, -1));

        jLabel28.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("Phone");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 90, 30));
        jPanel2.add(TextVetClinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        jLabel27.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("Clinic's Name");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 30));
        jPanel2.add(TextVetLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, -1));

        jLabel26.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 153));
        jLabel26.setText("Last Name");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 70, 30));
        jPanel2.add(TextVetFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        jLabel25.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("First Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 30));

        ButtonCreateAccount.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCreateAccount.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        ButtonCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCreateAccount.setText("REGISTER");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);
        jPanel2.add(ButtonCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 120, 40));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Roboto SemiBold", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("REGISTER VETERINARIAN");
        jLabel24.setOpaque(true);
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 530, 40));

        jLabel9.setBackground(new java.awt.Color(204, 204, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/istockphoto-1359095204-612x612.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -110, 410, 830));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCountry3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCountry3ActionPerformed

    }//GEN-LAST:event_ComboCountry3ActionPerformed

    private void ComboProvince3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvince3ActionPerformed

    }//GEN-LAST:event_ComboProvince3ActionPerformed

    private void ComboCanton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCanton3ActionPerformed

    }//GEN-LAST:event_ComboCanton3ActionPerformed

    private void TextVetLoctaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVetLoctaionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVetLoctaionActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
           // espera
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterVeterinarian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JComboBox<DbObject> ComboCanton3;
    private javax.swing.JComboBox<DbObject> ComboCountry3;
    private javax.swing.JComboBox<DbObject> ComboDistrict;
    private javax.swing.JComboBox<DbObject> ComboProvince3;
    private javax.swing.JLabel LabelCanton3;
    private javax.swing.JLabel LabelCountry3;
    private javax.swing.JLabel LabelDistrict3;
    private javax.swing.JLabel LabelProvince3;
    private javax.swing.JTextField TextPhoneVet;
    private javax.swing.JTextField TextVetClinicName;
    private javax.swing.JTextField TextVetFirstName;
    private javax.swing.JTextField TextVetLastName;
    private javax.swing.JTextField TextVetLoctaion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
