/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;
import animalwelfare.access.DbObject;
import animalwelfare.business.SignUpController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListCellRenderer;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author carlo
 */
public class SignUpForm extends javax.swing.JFrame {
    
    // esto es para imprimir mensajes de depuracion.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpForm.class.getName());
    
    // controlador
    private SignUpController controller = null;

    // modelo
    private DefaultListModel<String> modelEmail = null;
    private DefaultListModel<String> modelPhone = null;

    // procedimiento que rellena el combobox de Country
    public void fillCountry(ArrayList<DbObject> listCountry) {
        ComboCountry.removeAllItems();
        ComboCountry.addItem(new DbObject(0,"-"));
        for (DbObject c : listCountry) {
            ComboCountry.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Province
    public void fillProvince(ArrayList<DbObject> listProvince) {
        ComboProvince.removeAllItems();
        ComboProvince.addItem(new DbObject(0,"-"));
        for (DbObject c : listProvince) {
            ComboProvince.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Canton
    public void fillCanton(ArrayList<DbObject> listCanton) {
        ComboCanton.removeAllItems();
        ComboCanton.addItem(new DbObject(0,"-"));
        for (DbObject c : listCanton) {
            ComboCanton.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de District
    public void fillDistrict(ArrayList<DbObject> listDistrict) {
        ComboDistrict.removeAllItems();
        ComboDistrict.addItem(new DbObject(0,"-"));
        for (DbObject c : listDistrict) {
            ComboDistrict.addItem(c);
        }
    }
    
    
    public SignUpForm() {
        initComponents();
        controller = new SignUpController(this);
        setLocationRelativeTo(null);
        modelEmail = new DefaultListModel<>();
        modelPhone = new DefaultListModel<>();
        ComboProvince.setEnabled(false);
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);
        
        // Diseño de las combo box
        ComboCountry.setBackground(new Color(255, 255, 255));
        ComboProvince.setBackground(new Color(255, 255, 255));
        ComboCanton.setBackground(new Color(255, 255, 255));
        ComboDistrict.setBackground(new Color(255, 255, 255));
        
        ListCellRenderer oldRenderer = ComboCountry.getRenderer();
        ComboCountry.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboProvince.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboCanton.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboDistrict.setRenderer(new ListCellRendererProxy(oldRenderer));
        // Diseño de las combo box
        
        // Restriciones y Filtros
        NoSpaceFilter spaceFilter = new NoSpaceFilter();
        ((AbstractDocument) TextPhone.getDocument()).setDocumentFilter(new NumericFilter());
        ((AbstractDocument) TextEmail.getDocument()).setDocumentFilter(spaceFilter);
        ((AbstractDocument) TextPassword.getDocument()).setDocumentFilter(spaceFilter);
        ((AbstractDocument) TextPasswordRE.getDocument()).setDocumentFilter(spaceFilter);

        
        setVisible(true);
    }
         
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        LabelSubTitle = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();
        TextFirstName = new javax.swing.JTextField();
        LabelField1 = new javax.swing.JLabel();
        TextLastName = new javax.swing.JTextField();
        LabelField2 = new javax.swing.JLabel();
        ComboCountry = new javax.swing.JComboBox<>();
        LabelCountry = new javax.swing.JLabel();
        ComboProvince = new javax.swing.JComboBox<>();
        LabelProvince = new javax.swing.JLabel();
        ComboCanton = new javax.swing.JComboBox<>();
        LabelCanton = new javax.swing.JLabel();
        ComboDistrict = new javax.swing.JComboBox<>();
        LabelDistrict = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelField3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        LabelField4 = new javax.swing.JLabel();
        TextPasswordRE = new javax.swing.JPasswordField();
        TextUserName = new javax.swing.JTextField();
        LabelField5 = new javax.swing.JLabel();
        TextPhone = new javax.swing.JTextField();
        LabelField6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPhone = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListEmail = new javax.swing.JList<>();
        ButtonAddPhone = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ButtonAddEmail = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LableTitle1 = new javax.swing.JLabel();
        LableTitle3 = new javax.swing.JLabel();
        ImagenBackGround = new javax.swing.JLabel();
        LableTitle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));
        PanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelForm.setBackground(new java.awt.Color(255, 255, 255));

        LabelSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextEmail.addActionListener(this::TextEmailActionPerformed);

        LabelField.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField.setForeground(new java.awt.Color(0, 102, 102));
        LabelField.setText("EMAIL(S)");

        ButtonCreateAccount.setBackground(new java.awt.Color(0, 102, 102));
        ButtonCreateAccount.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        ButtonCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCreateAccount.setText("CREATE YOUR ACCOUNT");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);

        TextFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextFirstName.setToolTipText("");
        TextFirstName.addActionListener(this::TextFirstNameActionPerformed);

        LabelField1.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField1.setForeground(new java.awt.Color(0, 102, 102));
        LabelField1.setText("FIRST NAME");

        TextLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextLastName.setToolTipText("");
        TextLastName.addActionListener(this::TextLastNameActionPerformed);

        LabelField2.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField2.setForeground(new java.awt.Color(0, 102, 102));
        LabelField2.setText("LAST NAME");

        ComboCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCountry.setOpaque(true);
        ComboCountry.setRequestFocusEnabled(false);
        ComboCountry.addActionListener(this::ComboCountryActionPerformed);

        LabelCountry.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelCountry.setForeground(new java.awt.Color(0, 102, 102));
        LabelCountry.setText("COUNTRY");

        ComboProvince.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProvince.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboProvince.setOpaque(true);
        ComboProvince.setRequestFocusEnabled(false);
        ComboProvince.addActionListener(this::ComboProvinceActionPerformed);

        LabelProvince.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelProvince.setForeground(new java.awt.Color(0, 102, 102));
        LabelProvince.setText("PROVINCE");

        ComboCanton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCanton.setOpaque(true);
        ComboCanton.setRequestFocusEnabled(false);
        ComboCanton.addActionListener(this::ComboCantonActionPerformed);

        LabelCanton.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelCanton.setForeground(new java.awt.Color(0, 102, 102));
        LabelCanton.setText("CANTON");

        ComboDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboDistrict.setOpaque(true);
        ComboDistrict.setRequestFocusEnabled(false);
        ComboDistrict.addActionListener(this::ComboDistrictActionPerformed);

        LabelDistrict.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelDistrict.setForeground(new java.awt.Color(0, 102, 102));
        LabelDistrict.setText("DISTRICT");

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Address Information");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("__________________________________________________________________________________________________________________________________________________");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LabelField3.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField3.setForeground(new java.awt.Color(0, 102, 102));
        LabelField3.setText("PASSWORD");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("User Information");

        TextPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPassword.setToolTipText("At least 6 characters.");

        LabelField4.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField4.setForeground(new java.awt.Color(0, 102, 102));
        LabelField4.setText("RE-ENTER PASSWORD");

        TextPasswordRE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TextUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextUserName.setToolTipText("");
        TextUserName.addActionListener(this::TextUserNameActionPerformed);

        LabelField5.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField5.setForeground(new java.awt.Color(0, 102, 102));
        LabelField5.setText("USERNAME");

        TextPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPhone.addActionListener(this::TextPhoneActionPerformed);

        LabelField6.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        LabelField6.setForeground(new java.awt.Color(0, 102, 102));
        LabelField6.setText("PHONE NUMBER(S)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("__________________________________________________________________________________________________________________________________________________");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jScrollPane1.setViewportView(ListPhone);

        jScrollPane2.setViewportView(ListEmail);

        ButtonAddPhone.setBackground(new java.awt.Color(0, 142, 142));
        ButtonAddPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddPhoneMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("+");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonAddPhoneLayout = new javax.swing.GroupLayout(ButtonAddPhone);
        ButtonAddPhone.setLayout(ButtonAddPhoneLayout);
        ButtonAddPhoneLayout.setHorizontalGroup(
            ButtonAddPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        ButtonAddPhoneLayout.setVerticalGroup(
            ButtonAddPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        ButtonAddEmail.setBackground(new java.awt.Color(0, 142, 142));
        ButtonAddEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddEmailMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("+");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonAddEmailLayout = new javax.swing.GroupLayout(ButtonAddEmail);
        ButtonAddEmail.setLayout(ButtonAddEmailLayout);
        ButtonAddEmailLayout.setHorizontalGroup(
            ButtonAddEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
        ButtonAddEmailLayout.setVerticalGroup(
            ButtonAddEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextUserName)
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelCanton)
                                        .addGap(157, 157, 157))
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(ComboCanton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(16, 16, 16)))
                                .addGap(8, 8, 8)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelDistrict)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(ComboDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCountry)
                                    .addComponent(ComboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelProvince)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextLastName)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelField2)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelField5)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelField3)
                                            .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextPasswordRE, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelField4))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelField)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                                        .addComponent(TextPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonAddPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))))))
                .addGap(55, 55, 55))
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField)
                    .addComponent(LabelField6))
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAddPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField1)
                    .addComponent(LabelField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(LabelField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextPasswordRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelField3)
                            .addComponent(LabelField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCountry)
                    .addComponent(LabelProvince))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCanton)
                            .addComponent(LabelDistrict))
                        .addGap(32, 32, 32))
                    .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PanelBackGround.add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 70, 450, 600));

        LableTitle1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LableTitle1.setForeground(new java.awt.Color(255, 255, 0));
        LableTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle1.setText("NOW!");
        PanelBackGround.add(LableTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        LableTitle3.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LableTitle3.setForeground(new java.awt.Color(255, 255, 255));
        LableTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle3.setText("SIGN UP ");
        PanelBackGround.add(LableTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        ImagenBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/grass.jpg"))); // NOI18N
        PanelBackGround.add(ImagenBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 690));

        LableTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LableTitle2.setForeground(new java.awt.Color(255, 255, 255));
        LableTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle2.setText("CREATE ACCOUNT");
        PanelBackGround.add(LableTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 20, 586, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        // boton que envia los datos del formulario a la capa de access para que los inserten en la base de datos
        DbObject District = (DbObject) ComboDistrict.getSelectedItem();
        char[] passwordCharecters = TextPassword.getPassword();
        char[] rePasswordCharecters = TextPasswordRE.getPassword();
        boolean correct = controller.InsertPerson(TextEmail.getText(),TextFirstName.getText(),TextLastName.getText(),new String(passwordCharecters),new String(rePasswordCharecters), TextUserName.getText(),District, TextPhone.getText());
        if (correct){
            SignInForm window = new SignInForm();
            dispose();
        }
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    private void TextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFirstNameActionPerformed

    private void TextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLastNameActionPerformed

    private void ComboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCountryActionPerformed
        // al seleccionar un pais, se llena el de province y se bloquea los siguientes.
        if (controller == null) return;
        DbObject country = (DbObject) ComboCountry.getSelectedItem();
        if (country == null) return;
        if (country.getId() == 0) {
            ComboProvince.setEnabled(false);
            ComboCanton.setEnabled(false);
            ComboDistrict.setEnabled(false);
            return;
        }
        ComboCanton.removeAllItems();
        ComboDistrict.removeAllItems();
        
        controller.FillProvince(this, country.getId());
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);
        ComboProvince.setEnabled(true);
    }//GEN-LAST:event_ComboCountryActionPerformed

    private void ComboProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvinceActionPerformed
        // al seleccionar una provincia, se llena el de canton y se bloquea los siguientes.
        DbObject province = (DbObject) ComboProvince.getSelectedItem();
        if (province == null) return;
        if (province.getId() == 0){
            ComboDistrict.setEnabled(false);
            ComboCanton.setEnabled(false);
            return;
        }
        ComboDistrict.removeAllItems();
        
        controller.FillCanton(this, province.getId());
        ComboDistrict.setEnabled(false);
        ComboCanton.setEnabled(true);
    }//GEN-LAST:event_ComboProvinceActionPerformed

    private void ComboCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCantonActionPerformed
        // al seleccionar un canton, se llena el de Distrito.
        DbObject canton = (DbObject) ComboCanton.getSelectedItem();
        if (canton == null) return;
        if (canton.getId() == 0) {
            ComboDistrict.setEnabled(false);
            return;
        }
        ComboDistrict.removeAllItems();
        
        controller.FillDistrict(this, canton.getId());
        ComboDistrict.setEnabled(true);
    }//GEN-LAST:event_ComboCantonActionPerformed

    private void TextUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUserNameActionPerformed

    private void TextPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPhoneActionPerformed

    private void ComboDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDistrictActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void ButtonAddPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddPhoneMouseClicked
        String phone = TextPhone.getText();

        if (phone != null && !phone.isEmpty()) {

            boolean exists = false;

            for (int i = 0; i < modelPhone.size(); i++) {

                String item = modelPhone.get(i);

                if (item.equals(phone)) {
                    exists = true;
                    break;
                }
            }

            if (!exists) {
                modelPhone.addElement(phone);
            }
        }
    }//GEN-LAST:event_ButtonAddPhoneMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void ButtonAddEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddEmailMouseClicked
        String email = TextEmail.getText();

        if (email != null && !email.isEmpty()) {

            boolean exists = false;

            for (int i = 0; i < modelEmail.size(); i++) {

                String item = modelEmail.get(i);

                if (item.equals(email)) {
                    exists = true;
                    break;
                }
            }

            if (!exists) {
                modelEmail.addElement(email);
            }
        }
    }//GEN-LAST:event_ButtonAddEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonAddEmail;
    private javax.swing.JPanel ButtonAddEmail1;
    private javax.swing.JPanel ButtonAddEmail2;
    private javax.swing.JPanel ButtonAddPhone;
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JComboBox<DbObject> ComboCanton;
    private javax.swing.JComboBox<DbObject> ComboCountry;
    private javax.swing.JComboBox<DbObject> ComboDistrict;
    private javax.swing.JComboBox<DbObject> ComboProvince;
    private javax.swing.JLabel ImagenBackGround;
    private javax.swing.JLabel LabelCanton;
    private javax.swing.JLabel LabelCountry;
    private javax.swing.JLabel LabelDistrict;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelField1;
    private javax.swing.JLabel LabelField2;
    private javax.swing.JLabel LabelField3;
    private javax.swing.JLabel LabelField4;
    private javax.swing.JLabel LabelField5;
    private javax.swing.JLabel LabelField6;
    private javax.swing.JLabel LabelProvince;
    private javax.swing.JLabel LabelSubTitle;
    private javax.swing.JLabel LableTitle1;
    private javax.swing.JLabel LableTitle2;
    private javax.swing.JLabel LableTitle3;
    private javax.swing.JList<String> ListEmail;
    private javax.swing.JList<String> ListPhone;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextFirstName;
    private javax.swing.JTextField TextLastName;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JPasswordField TextPasswordRE;
    private javax.swing.JTextField TextPhone;
    private javax.swing.JTextField TextUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
