package animalwelfare.userInterface;

import animalwelfare.business.SignInController;


public class SignInForm extends javax.swing.JFrame {
    

    // cotrolador
    private SignInController controller = null;
    
    
    
    
    public SignInForm() {
        initComponents();
        controller = new SignInController();
        setLocationRelativeTo(null);
        setVisible(true);
        requestFocusInWindow();
        
        // button changes
        // esto evita el diseño raro
        ButtonCreateAccount.setFocusPainted(false);
        ButtonCreateAccount.setBorderPainted(false);
        ButtonCreateAccount.setContentAreaFilled(false);
        ButtonCreateAccount.setOpaque(true);
        
        ButtonContinue.setFocusPainted(false);
        ButtonContinue.setBorderPainted(false);
        ButtonContinue.setContentAreaFilled(false);
        ButtonContinue.setOpaque(true);

        // Placeholder text for username and password fields
        TextUserName.setText("Enter your user");
        TextPassword.setText("********");

        TextUserName.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {

                if (TextUserName.getText().equals("Enter your user")) {
                    TextUserName.setText("");
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {

                if (TextUserName.getText().isEmpty()) {
                    TextUserName.setText("Enter your user");
                }
            }
        });

        TextPassword.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {

                if (String.valueOf(TextPassword.getPassword()).equals("********")) {
                    TextPassword.setText("");
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {

                if (String.valueOf(TextPassword.getPassword()).isEmpty()) {
                    TextPassword.setText("********");
                }
            }
        });

        
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        TextUserName = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonContinue = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();
        LabelField1 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        LabelField2 = new javax.swing.JLabel();
        LabelField3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));

        PanelForm.setBackground(new java.awt.Color(0, 153, 153));
        PanelForm.setForeground(new java.awt.Color(255, 255, 255));

        TextUserName.setBackground(new java.awt.Color(0, 153, 153));
        TextUserName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        TextUserName.setForeground(new java.awt.Color(255, 255, 255));
        TextUserName.setToolTipText("");
        TextUserName.setBorder(null);
        TextUserName.addActionListener(this::TextUserNameActionPerformed);

        LabelField.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LabelField.setForeground(new java.awt.Color(255, 255, 255));
        LabelField.setText("PASSWORD");

        ButtonContinue.setBackground(new java.awt.Color(254, 255, 255));
        ButtonContinue.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ButtonContinue.setForeground(new java.awt.Color(0, 121, 121));
        ButtonContinue.setText("CONTINUE");
        ButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonContinue.addActionListener(this::ButtonContinueActionPerformed);

        LableTitle.setFont(new java.awt.Font("Roboto SemiBold", 0, 36)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 255, 255));
        LableTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LableTitle.setText("ANIMAL WELFARE");

        LabelField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField1.setForeground(new java.awt.Color(255, 255, 255));
        LabelField1.setText("USERNAME");

        TextPassword.setBackground(new java.awt.Color(0, 153, 153));
        TextPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        TextPassword.setForeground(new java.awt.Color(255, 255, 255));
        TextPassword.setToolTipText("");
        TextPassword.setBorder(null);
        TextPassword.addActionListener(this::TextPasswordActionPerformed);

        LabelField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField2.setForeground(new java.awt.Color(255, 255, 255));
        LabelField2.setText("_________________________________________________________________________");
        LabelField2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LabelField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField3.setForeground(new java.awt.Color(255, 255, 255));
        LabelField3.setText("_________________________________________________________________________");
        LabelField3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/banner_image.jpg"))); // NOI18N

        ButtonCreateAccount.setBackground(new java.awt.Color(242, 242, 242));
        ButtonCreateAccount.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ButtonCreateAccount.setForeground(new java.awt.Color(0, 121, 121));
        ButtonCreateAccount.setText("CREATE");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);

        jLabel2.setFont(new java.awt.Font("Roboto ExtraLight", 2, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Having issues while logging in?");

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelField2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelField1)
                                .addComponent(LabelField)
                                .addComponent(TextUserName)
                                .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelFormLayout.createSequentialGroup()
                                    .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1))
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LableTitle)
                .addGap(57, 57, 57)
                .addComponent(LabelField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelField3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelField2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelBackGroundLayout = new javax.swing.GroupLayout(PanelBackGround);
        PanelBackGround.setLayout(PanelBackGroundLayout);
        PanelBackGroundLayout.setHorizontalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBackGroundLayout.setVerticalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUserNameActionPerformed

    private void ButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContinueActionPerformed
        String email = TextUserName.getText();
        char[] passwordCharecters = TextPassword.getPassword();
        String password = new String(passwordCharecters);
        if(controller.CheckUser(email, password)){
            MainMenu window = new MainMenu();
            dispose();
        }
    }//GEN-LAST:event_ButtonContinueActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        SignUpForm window = new SignUpForm();
        dispose();
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    private void TextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContinue;
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelField1;
    private javax.swing.JLabel LabelField2;
    private javax.swing.JLabel LabelField3;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JTextField TextUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
