/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalwelfare.userInterface;
import animalwelfare.access.Location;
import animalwelfare.business.SignUp;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ListCellRenderer;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author carlo
 */
public class SignUpForm extends javax.swing.JFrame {
    
    // esto es para imprimir mensajes de depuracion.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpForm.class.getName());
    
    // controlador
    private SignUp controller = null;

    // procedimiento que rellena el combobox de Country
    public void fillCountry(ArrayList<Location> listCountry) {
        ComboCountry.removeAllItems();
        ComboCountry.addItem(new Location(0,"-"));
        for (Location c : listCountry) {
            ComboCountry.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Country
    public void fillProvince(ArrayList<Location> listCountry) {
        ComboProvince.removeAllItems();
        ComboProvince.addItem(new Location(0,"-"));
        for (Location c : listCountry) {
            ComboProvince.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Country
    public void fillCanton(ArrayList<Location> listCountry) {
        ComboCanton.removeAllItems();
        ComboCanton.addItem(new Location(0,"-"));
        for (Location c : listCountry) {
            ComboCanton.addItem(c);
        }
    }
    
    // procedimiento que rellena el combobox de Country
    public void fillDistrict(ArrayList<Location> listCountry) {
        ComboDistrict.removeAllItems();
        ComboDistrict.addItem(new Location(0,"-"));
        for (Location c : listCountry) {
            ComboDistrict.addItem(c);
        }
    }
    
    
    public SignUpForm() {
        initComponents();
        controller = new SignUp(this);
        setLocationRelativeTo(null);
        
        ComboProvince.setEnabled(false);
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);
        
        // Diseño de las combo box
        ComboCountry.setBackground(new Color(255, 255, 255));
        ComboProvince.setBackground(new Color(255, 255, 255));
        ComboCanton.setBackground(new Color(255, 255, 255));
        ComboDistrict.setBackground(new Color(255, 255, 255));
        
        ListCellRenderer oldRenderer = ComboCountry.getRenderer();
        ComboCountry.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboProvince.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboCanton.setRenderer(new ListCellRendererProxy(oldRenderer));
        ComboDistrict.setRenderer(new ListCellRendererProxy(oldRenderer));
        // Diseño de las combo box
        
        // Restriciones y Filtros
        NoSpaceFilter spaceFilter = new NoSpaceFilter();
        ((AbstractDocument) TextPhone.getDocument()).setDocumentFilter(new NumericFilter());
        ((AbstractDocument) TextEmail.getDocument()).setDocumentFilter(spaceFilter);
        ((AbstractDocument) TextPassword.getDocument()).setDocumentFilter(spaceFilter);
        ((AbstractDocument) TextPasswordRE.getDocument()).setDocumentFilter(spaceFilter);

        
        setVisible(true);
    }
         
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        LabelSubTitle = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonCreateAccount = new javax.swing.JButton();
        TextFirstName = new javax.swing.JTextField();
        LabelField1 = new javax.swing.JLabel();
        TextLastName = new javax.swing.JTextField();
        LabelField2 = new javax.swing.JLabel();
        ComboCountry = new javax.swing.JComboBox<>();
        LabelCountry = new javax.swing.JLabel();
        ComboProvince = new javax.swing.JComboBox<>();
        LabelProvince = new javax.swing.JLabel();
        ComboCanton = new javax.swing.JComboBox<>();
        LabelCanton = new javax.swing.JLabel();
        ComboDistrict = new javax.swing.JComboBox<>();
        LabelDistrict = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelField3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        LabelField4 = new javax.swing.JLabel();
        TextPasswordRE = new javax.swing.JPasswordField();
        TextUserName = new javax.swing.JTextField();
        LabelField5 = new javax.swing.JLabel();
        TextPhone = new javax.swing.JTextField();
        LabelField6 = new javax.swing.JLabel();
        LableTitle = new javax.swing.JLabel();
        ImagenBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));
        PanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTitle.setText("Create account");

        TextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextEmail.addActionListener(this::TextEmailActionPerformed);

        LabelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField.setText("Enter your email");

        ButtonCreateAccount.setBackground(new java.awt.Color(255, 216, 20));
        ButtonCreateAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonCreateAccount.setText("Create your account");
        ButtonCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCreateAccount.addActionListener(this::ButtonCreateAccountActionPerformed);

        TextFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextFirstName.setToolTipText("");
        TextFirstName.addActionListener(this::TextFirstNameActionPerformed);

        LabelField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField1.setText("First name");

        TextLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextLastName.setToolTipText("");
        TextLastName.addActionListener(this::TextLastNameActionPerformed);

        LabelField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField2.setText("Last name");

        ComboCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCountry.setOpaque(true);
        ComboCountry.setRequestFocusEnabled(false);
        ComboCountry.addActionListener(this::ComboCountryActionPerformed);

        LabelCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCountry.setText("Country");

        ComboProvince.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProvince.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboProvince.setOpaque(true);
        ComboProvince.setRequestFocusEnabled(false);
        ComboProvince.addActionListener(this::ComboProvinceActionPerformed);

        LabelProvince.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelProvince.setText("Province");

        ComboCanton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboCanton.setOpaque(true);
        ComboCanton.setRequestFocusEnabled(false);
        ComboCanton.addActionListener(this::ComboCantonActionPerformed);

        LabelCanton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCanton.setText("Canton");

        ComboDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboDistrict.setOpaque(true);
        ComboDistrict.setRequestFocusEnabled(false);

        LabelDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelDistrict.setText("District");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Address");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("__________________________________________________________________________________________________________________________________________________");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LabelField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField3.setText("Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("______________________________________________________________________________________________________________________________");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("User");

        TextPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPassword.setToolTipText("At least 6 characters.");

        LabelField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField4.setText("Re-enter password");

        TextPasswordRE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TextUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextUserName.setToolTipText("");
        TextUserName.addActionListener(this::TextUserNameActionPerformed);

        LabelField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField5.setText("User name");

        TextPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPhone.addActionListener(this::TextPhoneActionPerformed);

        LabelField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelField6.setText("Phone Number");

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelField1)
                                    .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(TextFirstName))
                                .addGap(18, 18, 18)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelField2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TextPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextLastName))
                                        .addGap(20, 20, 20))))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addComponent(LabelCountry)
                                                .addGap(164, 164, 164))
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addComponent(ComboCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addComponent(LabelProvince)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelCanton)
                                            .addComponent(ComboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(PanelFormLayout.createSequentialGroup()
                                                .addComponent(LabelDistrict)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelField3)
                                            .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextPasswordRE, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelField4))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextUserName))
                                .addGap(20, 20, 20))
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelField5)
                                    .addGroup(PanelFormLayout.createSequentialGroup()
                                        .addComponent(LabelField)
                                        .addGap(112, 112, 112)
                                        .addComponent(LabelField6))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubTitle)
                .addGap(18, 18, 18)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField)
                    .addComponent(LabelField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelField1)
                    .addComponent(LabelField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextPasswordRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelField3)
                            .addComponent(LabelField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProvince, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ComboProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addComponent(LabelCanton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addComponent(LabelDistrict)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(ButtonCreateAccount)
                .addGap(20, 20, 20))
        );

        PanelBackGround.add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 70, -1, -1));

        LableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LableTitle.setForeground(new java.awt.Color(255, 255, 255));
        LableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LableTitle.setText("Animal Welfare");
        PanelBackGround.add(LableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 20, 586, -1));

        ImagenBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalwelfare/userInterface/images/backgroundForm.jpg"))); // NOI18N
        PanelBackGround.add(ImagenBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        // boton que envia los datos del formulario a la capa de access para que los inserten en la base de datos
        Location District = (Location) ComboDistrict.getSelectedItem();
        char[] passwordCharecters = TextPassword.getPassword();
        char[] rePasswordCharecters = TextPasswordRE.getPassword();
        boolean correct = controller.InsertPerson(TextEmail.getText(),TextFirstName.getText(),TextLastName.getText(),new String(passwordCharecters),new String(rePasswordCharecters), TextUserName.getText(),District, TextPhone.getText());
        if (correct){
            SignInForm window = new SignInForm();
            dispose();
        }
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    private void TextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFirstNameActionPerformed

    private void TextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLastNameActionPerformed

    private void ComboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCountryActionPerformed
        // al seleccionar un pais, se llena el de province y se bloquea los siguientes.
        if (controller == null) return;
        Location country = (Location) ComboCountry.getSelectedItem();
        if (country == null) return;
        if (country.getId() == 0) return;
        ComboCanton.removeAllItems();
        ComboDistrict.removeAllItems();
        
        controller.FillProvince(this, country.getId());
        ComboCanton.setEnabled(false);
        ComboDistrict.setEnabled(false);
        ComboProvince.setEnabled(true);
    }//GEN-LAST:event_ComboCountryActionPerformed

    private void ComboProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProvinceActionPerformed
        // al seleccionar una provincia, se llena el de canton y se bloquea los siguientes.
        Location province = (Location) ComboProvince.getSelectedItem();
        if (province == null) return;
        if (province.getId() == 0) return;
        ComboDistrict.removeAllItems();
        
        controller.FillCanton(this, province.getId());
        ComboDistrict.setEnabled(false);
        ComboCanton.setEnabled(true);
    }//GEN-LAST:event_ComboProvinceActionPerformed

    private void ComboCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCantonActionPerformed
        // al seleccionar un canton, se llena el de Distrito.
        Location canton = (Location) ComboCanton.getSelectedItem();
        if (canton == null) return;
        if (canton.getId() == 0) return;
        ComboDistrict.removeAllItems();
        
        controller.FillDistrict(this, canton.getId());
        ComboDistrict.setEnabled(true);
    }//GEN-LAST:event_ComboCantonActionPerformed

    private void TextUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUserNameActionPerformed

    private void TextPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JComboBox<Location> ComboCanton;
    private javax.swing.JComboBox<Location> ComboCountry;
    private javax.swing.JComboBox<Location> ComboDistrict;
    private javax.swing.JComboBox<Location> ComboProvince;
    private javax.swing.JLabel ImagenBackGround;
    private javax.swing.JLabel LabelCanton;
    private javax.swing.JLabel LabelCountry;
    private javax.swing.JLabel LabelDistrict;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelField1;
    private javax.swing.JLabel LabelField2;
    private javax.swing.JLabel LabelField3;
    private javax.swing.JLabel LabelField4;
    private javax.swing.JLabel LabelField5;
    private javax.swing.JLabel LabelField6;
    private javax.swing.JLabel LabelProvince;
    private javax.swing.JLabel LabelSubTitle;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextFirstName;
    private javax.swing.JTextField TextLastName;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JPasswordField TextPasswordRE;
    private javax.swing.JTextField TextPhone;
    private javax.swing.JTextField TextUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
