ALTER TABLE PetLevelEnergy MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetBreed       MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetType        MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetState       MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetIllness     MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetTreatment   MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetTraining    MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE SpaceRequired  MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetSize        MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE PetSeverity    MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE Currency       MODIFY COLUMN Name VARCHAR(25) NOT NULL;
ALTER TABLE Medicine       MODIFY COLUMN Name VARCHAR(25) NOT NULL;

ALTER TABLE PetLevelEnergy ADD CONSTRAINT uq_PetLevelEnergy_Name UNIQUE (Name);
ALTER TABLE PetBreed       ADD CONSTRAINT uq_PetBreed_Name       UNIQUE (Name);
ALTER TABLE PetType        ADD CONSTRAINT uq_PetType_Name        UNIQUE (Name);
ALTER TABLE PetState       ADD CONSTRAINT uq_PetState_Name       UNIQUE (Name);
ALTER TABLE PetSeverity    ADD CONSTRAINT uq_PetSeverity_Name    UNIQUE (Name);
ALTER TABLE Currency       ADD CONSTRAINT uq_Currency_Name       UNIQUE (Name);

ALTER TABLE Country
MODIFY COLUMN Name VARCHAR(25) NOT NULL;

ALTER TABLE Province
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN IdCountry INT NOT NULL;

ALTER TABLE Canton
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN IdProvince INT NOT NULL;

ALTER TABLE District
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN IdCanton INT NOT NULL;

ALTER TABLE Person
MODIFY COLUMN FirstName VARCHAR(25) NOT NULL,
MODIFY COLUMN LastName VARCHAR(25) NOT NULL,
MODIFY COLUMN Password VARCHAR(60) NOT NULL,
MODIFY COLUMN UserName VARCHAR(25) NOT NULL,
MODIFY COLUMN IdDistrict INT NOT NULL;

ALTER TABLE Person
ADD CONSTRAINT uq_Person_UserName UNIQUE (UserName);

ALTER TABLE PetBreed
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN IdType INT NOT NULL;

ALTER TABLE Email
MODIFY COLUMN Email VARCHAR(25) NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Phone
MODIFY COLUMN Phone INT NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Email
ADD CONSTRAINT chk_Email_Format
CHECK (Email LIKE '%@%.%');

ALTER TABLE Email
ADD CONSTRAINT uq_Email UNIQUE (Email);

ALTER TABLE Pet
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN Color VARCHAR(50) NOT NULL,
MODIFY COLUMN IdState INT NOT NULL,
MODIFY COLUMN IdType INT NOT NULL;

ALTER TABLE Pet
ADD CONSTRAINT uq_Pet_Chip UNIQUE (Chip);

ALTER TABLE Pet
ADD CONSTRAINT chk_Pet_Age
CHECK (Age IS NULL OR Age >= 0);

ALTER TABLE PetPhoto
MODIFY COLUMN Photo VARCHAR(255) NOT NULL,
MODIFY COLUMN IdPet INT NOT NULL;

ALTER TABLE Veterinarian
MODIFY COLUMN Name VARCHAR(50) NOT NULL,
MODIFY COLUMN FirstName VARCHAR(25) NOT NULL,
MODIFY COLUMN LastName VARCHAR(25) NOT NULL;

ALTER TABLE Veterinarian
ADD CONSTRAINT chk_Veterinarian_Email
CHECK (Email IS NULL OR Email LIKE '%@%.%');

ALTER TABLE FosterHome
MODIFY COLUMN NeedsDonation VARCHAR(1) NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE FosterHome
ADD CONSTRAINT chk_FosterHome_NeedsDonation
CHECK (NeedsDonation IN ('Y', 'N'));

ALTER TABLE LostReport
MODIFY COLUMN LostDate DATE NOT NULL,
MODIFY COLUMN IdPet INT NOT NULL,
MODIFY COLUMN IdCurrency INT NOT NULL;

ALTER TABLE LostReport
ADD CONSTRAINT chk_LostReport_Reward
CHECK (Reward IS NULL OR Reward >= 0);

ALTER TABLE FoundReport
MODIFY COLUMN FoundDate DATE NOT NULL,
MODIFY COLUMN IdPet INT NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE PetMatch
MODIFY COLUMN MatchDate DATE NOT NULL,
MODIFY COLUMN IdLostReport INT NOT NULL,
MODIFY COLUMN IdFoundReport INT NOT NULL,
MODIFY COLUMN SimilarityPercentage INT NOT NULL;

ALTER TABLE PetMatch
ADD CONSTRAINT chk_PetMatch_Percentage
CHECK (SimilarityPercentage BETWEEN 0 AND 100);

ALTER TABLE Adoption
MODIFY COLUMN IdAdopter INT NULL;

ALTER TABLE Veterinarian
MODIFY COLUMN Location VARCHAR(1000),
MODIFY COLUMN Phone BIGINT;

ALTER TABLE Adoption
MODIFY COLUMN AvailableDate DATE NOT NULL,
MODIFY COLUMN IdPet INT NOT NULL,
MODIFY COLUMN IdAdopter INT NULL,
MODIFY COLUMN IdOwner INT NOT NULL;

ALTER TABLE Adoption
ADD CONSTRAINT chk_Adoption_State
CHECK (State IN ('In progress', 'Adopted', 'Cancelled'));

ALTER TABLE Adoption
ADD CONSTRAINT chk_Adoption_Dates
CHECK (
    AvailableDate IS NULL
    OR AdoptionDate IS NULL
    OR AvailableDate <= AdoptionDate
);

ALTER TABLE Rescued
MODIFY COLUMN RescueDate DATE NOT NULL,
MODIFY COLUMN IdPet INT NOT NULL,
MODIFY COLUMN IdRescuer INT NOT NULL,
MODIFY COLUMN IdPetSeverity INT NOT NULL;

ALTER TABLE Donation
MODIFY COLUMN Amount INT NOT NULL,
MODIFY COLUMN DonationDate DATE NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL,
MODIFY COLUMN IdCurrency INT NOT NULL,
MODIFY COLUMN IdAssociation INT NOT NULL;

ALTER TABLE Donation
ADD CONSTRAINT chk_Donation_Amount
CHECK (Amount > 0);

ALTER TABLE Association
MODIFY COLUMN Name VARCHAR(25) NOT NULL;

ALTER TABLE Association
ADD CONSTRAINT uq_Association_Name UNIQUE (Name);

ALTER TABLE Association
ADD CONSTRAINT chk_Association_Email
CHECK (Email IS NULL OR Email LIKE '%@%.%');

ALTER TABLE Calification
MODIFY COLUMN Stars INT NOT NULL,
MODIFY COLUMN CalificationDate DATE NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Calification
ADD CONSTRAINT chk_Calification_Stars
CHECK (Stars BETWEEN 1 AND 5);

ALTER TABLE ReportList
MODIFY COLUMN IdPerson INT NOT NULL,
MODIFY COLUMN IdReporter INT NOT NULL,
MODIFY COLUMN ReportDate DATE NOT NULL;

ALTER TABLE ReportList
ADD CONSTRAINT chk_ReportList_SelfReport
CHECK (IdPerson <> IdReporter);

ALTER TABLE BlockList
MODIFY COLUMN BlockDate DATE NOT NULL,
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Parameter
MODIFY COLUMN Name VARCHAR(25) NOT NULL,
MODIFY COLUMN Value INT NOT NULL;

ALTER TABLE Parameter
ADD CONSTRAINT uq_Parameter_Name UNIQUE (Name);

ALTER TABLE Bitacora
MODIFY COLUMN TableName VARCHAR(25) NOT NULL,
MODIFY COLUMN ChangeDate DATE NOT NULL,
MODIFY COLUMN ChangedBy INT NOT NULL,
MODIFY COLUMN FieldName VARCHAR(25) NOT NULL;

ALTER TABLE Rescuer
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Adopter
MODIFY COLUMN IdPerson INT;

ALTER TABLE Admin
MODIFY COLUMN IdPerson INT NOT NULL;

ALTER TABLE Rescuer
ADD CONSTRAINT uq_Rescuer_Person UNIQUE (IdPerson);

ALTER TABLE Adopter
ADD CONSTRAINT uq_Adopter_Person UNIQUE (IdPerson);

ALTER TABLE Admin
ADD CONSTRAINT uq_Admin_Person UNIQUE (IdPerson);

ALTER TABLE FosterHome
ADD CONSTRAINT uq_FosterHome_Person UNIQUE (IdPerson);