package bienestaranimal.userInterface;


public class EnterEmail extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public EnterEmail() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackGround = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        LabelSubTitle = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelField = new javax.swing.JLabel();
        ButtonContinue = new javax.swing.JButton();
        LableTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        PanelBackGround.setBackground(new java.awt.Color(204, 204, 204));

        LabelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubTitle.setText("Sign in ");

        TextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextEmail.addActionListener(this::TextEmailActionPerformed);

        LabelField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelField.setText("Enter your User name");

        ButtonContinue.setBackground(new java.awt.Color(255, 216, 20));
        ButtonContinue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonContinue.setText("Continue");
        ButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonContinue.addActionListener(this::ButtonContinueActionPerformed);

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelField)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelField)
                .addGap(1, 1, 1)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(ButtonContinue)
                .addGap(20, 20, 20))
        );

        LableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LableTitle.setText("Animal Welfare");

        javax.swing.GroupLayout PanelBackGroundLayout = new javax.swing.GroupLayout(PanelBackGround);
        PanelBackGround.setLayout(PanelBackGroundLayout);
        PanelBackGroundLayout.setHorizontalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBackGroundLayout.createSequentialGroup()
                .addGroup(PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBackGroundLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(LableTitle))
                    .addGroup(PanelBackGroundLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(PanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PanelBackGroundLayout.setVerticalGroup(
            PanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBackGroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LableTitle)
                .addGap(18, 18, 18)
                .addComponent(PanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void ButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContinueActionPerformed
        SignUpForm window = new SignUpForm(TextEmail.getText());
        dispose();
    }//GEN-LAST:event_ButtonContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContinue;
    private javax.swing.JLabel LabelField;
    private javax.swing.JLabel LabelSubTitle;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JPanel PanelBackGround;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JTextField TextEmail;
    // End of variables declaration//GEN-END:variables
}
